"""initial tables

Revision ID: 9ae0bc9a1a92
Revises:
Create Date: 2026-08-20 22:08:59.623650

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ae0bc9a1a92'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user_id', table_name='audit_logs')
    op.drop_index('idx_documents_exam_id', table_name='documents')
    op.drop_constraint('exam_assignments_exam_id_exam_student_id_key', 'exam_assignments', type_='unique')
    op.drop_constraint('exam_assignments_exam_id_seat_id_key', 'exam_assignments', type_='unique')
    op.drop_index('idx_exam_assignments_exam_id', table_name='exam_assignments')
    op.drop_index('idx_exam_assignments_seat_id', table_name='exam_assignments')
    op.create_unique_constraint('uq_exam_exam_student', 'exam_assignments', ['exam_id', 'exam_student_id'])
    op.create_unique_constraint('uq_exam_seat', 'exam_assignments', ['exam_id', 'seat_id'])
    op.drop_constraint('exam_students_exam_id_student_id_key', 'exam_students', type_='unique')
    op.drop_index('idx_exam_students_exam_id', table_name='exam_students')
    op.drop_index('idx_exam_students_student_id', table_name='exam_students')
    op.create_unique_constraint('uq_exam_student', 'exam_students', ['exam_id', 'student_id'])
    op.drop_constraint('rooms_building_room_number_key', 'rooms', type_='unique')
    op.create_unique_constraint('uq_building_room', 'rooms', ['building', 'room_number'])
    op.drop_index('idx_seats_room_id', table_name='seats')
    op.drop_constraint('seats_room_id_seat_code_key', 'seats', type_='unique')
    op.create_unique_constraint('uq_room_seat', 'seats', ['room_id', 'seat_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_room_seat', 'seats', type_='unique')
    op.create_unique_constraint('seats_room_id_seat_code_key', 'seats', ['room_id', 'seat_code'])
    op.create_index('idx_seats_room_id', 'seats', ['room_id'], unique=False)
    op.drop_constraint('uq_building_room', 'rooms', type_='unique')
    op.create_unique_constraint('rooms_building_room_number_key', 'rooms', ['building', 'room_number'])
    op.drop_constraint('uq_exam_student', 'exam_students', type_='unique')
    op.create_index('idx_exam_students_student_id', 'exam_students', ['student_id'], unique=False)
    op.create_index('idx_exam_students_exam_id', 'exam_students', ['exam_id'], unique=False)
    op.create_unique_constraint('exam_students_exam_id_student_id_key', 'exam_students', ['exam_id', 'student_id'])
    op.drop_constraint('uq_exam_seat', 'exam_assignments', type_='unique')
    op.drop_constraint('uq_exam_exam_student', 'exam_assignments', type_='unique')
    op.create_index('idx_exam_assignments_seat_id', 'exam_assignments', ['seat_id'], unique=False)
    op.create_index('idx_exam_assignments_exam_id', 'exam_assignments', ['exam_id'], unique=False)
    op.create_unique_constraint('exam_assignments_exam_id_seat_id_key', 'exam_assignments', ['exam_id', 'seat_id'])
    op.create_unique_constraint(
        'exam_assignments_exam_id_exam_student_id_key', 'exam_assignments', ['exam_id', 'exam_student_id']
    )
    op.create_index('idx_documents_exam_id', 'documents', ['exam_id'], unique=False)
    op.create_index('idx_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
